version: '3'

services:
  mongo:
    container_name: mongo_container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
    restart: always

  app:
    container_name: api_container
    build: .
    environment:
      MONGO_URL: mongodb://mongo:27018/Note_data
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    restart: always

volumes:
  mongodb:
